# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/featsql',
                'doc_host': 'https://ravennaro.github.io',
                'git_url': 'https://github.com/ravennaro/featsql',
                'lib_path': 'featsql'},
  'syms': { 'featsql.core': { 'featsql.core.create_query_cat': ('core.html#create_query_cat', 'featsql/core.py'),
                              'featsql.core.create_query_num': ('core.html#create_query_num', 'featsql/core.py'),
                              'featsql.core.func_query_janela_cat': ('core.html#func_query_janela_cat', 'featsql/core.py'),
                              'featsql.core.func_query_janela_num': ('core.html#func_query_janela_num', 'featsql/core.py'),
                              'featsql.core.func_query_join_num': ('core.html#func_query_join_num', 'featsql/core.py')}}}
