# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/featsql',
                'doc_host': 'https://ravennaro.github.io',
                'git_url': 'https://github.com/ravennaro/featsql',
                'lib_path': 'featsql'},
  'syms': {'featsql.core': {'featsql.core.foo': ('core.html#foo', 'featsql/core.py')}}}
